services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    environment:
      - DATABASE_URL=postgresql://n8n:n8n@postgres:5432/postgres
      - DATABASE_URL=
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_ENCRYPTION_KEY=your-secret-key
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - NODE_FUNCTION_ALLOW_EXTERNAL_FUNCTIONS=true
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - n8n-network

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - caddy_config:/etc/caddy
    networks:
      - n8n-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge

volumes:
  redis_data:
  caddy_data:
  caddy_config: