services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
    env_file:
      - stack.env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - n8n-network

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - caddy_config:/etc/caddy
    networks:
      - n8n-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge

volumes:
  redis_data:
  caddy_data:
  caddy_config: