services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - N8N_HOST=n8n.onrise.dev
    env_file:
      - stack.env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - n8n-network

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - ./caddy_config:/etc/caddy
      - ./caddy_config/Caddyfile:/etc/caddy/Caddyfile

    networks:
      - n8n-network
    depends_on:
      - n8n

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge

volumes:
  redis_data:
  caddy_data:
  caddy_config: